#!/bin/sh 

# Copyright (c) 2017-2018, Exile Heavy Industries
# All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted (subject to the limitations in the disclaimer
# below) provided that the following conditions are met:
# 
# * Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
# 
# * Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
# 
# * Neither the name of the copyright holder nor the names of its contributors may be used
#   to endorse or promote products derived from this software without specific
#   prior written permission.
# 
# NO EXPRESS OR IMPLIED LICENSES TO ANY PARTY'S PATENT RIGHTS ARE GRANTED BY THIS
# LICENSE. THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
# GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
# OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
# DAMAGE.

host=0
table=0
tabledir="/etc/tables"
direct_edit=1

edit_mode() {
	echo "editing $table directly"
	## Use some sane editor commands regardless of what's set by the user
	if [[ "$table" != "0" ]]
	then
		case "${EDITOR}" in 
			"nano") 
				/usr/local/bin/nano $tabledir/$table
			;;
			"vim")
				if [ -f $HOME/.vimrc ]
				then
					/usr/local/bin/vim -u $HOME/.vimrc $tabledir/$table
				else
					/usr/local/bin/vim $tabledir/$table
				fi
			;;
			"ed")
				/bin/ed $tabledir/$table
			;;
			"vi")
				/usr/bin/vi $tabledir/$table
			;;
			"micro")
				/usr/local/bin/micro $tabledir/$table
			;;
			"nvim")
				if [ -f $HOME/.vimrc ] 
				then
					/usr/local/bin/nvim -u $HOME/.vimrc $tabledir/$table
				elif [ -f $HOME/.config/nvim/init.vim ]
				then
					/usr/local/bin/nvim -u $HOME/.config/nvim/init.vim $tabledir/$table
				else
					/usr/local/bin/nvim $tabledir/$table
				fi
			;;
			*)
				/usr/local/bin/vim -u /etc/vimrc $tabledir/$table
			;;
		esac
		/sbin/pfctl -vvvndf /etc/pf.conf
		if [ $? -eq 0 ]
		then
			/sbin/pfctl -f /etc/pf.conf
		fi
	else
		echo "You must specify a table"
		exit 1
	fi
}

run_help() {
	## display basic help info ## 
	echo -e "Add a host to a pf table"
	echo -e "\t-a\tThe address to add (CIDR notation is accepted)"
	echo -e "\t-e\tLaunch $EDITOR to add entries to a table (requires -t)"
	echo -e "\t-h\tThis text"
	echo -e "\t-t\tThe table to add this address into"
	echo -e "\n\tEx: host_add -h 192.168.1.0/24 -t allowed"
	exit 0
}

verify() {
	## verify that this is a valid use of the script
	if [ $table != 0 ]
	then
			if [ $(id -u) -ne 0 ]
			then
				echo "You must be root to run this script"
				exit 1	
			fi
			if [ $direct_edit -eq 0 ]
			then
				edit_mode
			else 
				case "$table" in
					"allowed")
						live_update
					;;
					"enforcers")
						nonvol_update
					;;
					"admins")
						nonvol_update
					;;
					"customers")
						nonvol_update
					;;
					0)
						echo "Invalid table"
						exit 2 
					;;
					\?)
						echo "Invalid table"
						exit 2
					;;
				esac
		fi
	else 
		printf "%s is not a valid table\n" $table
		run_help
	fi
}

nonvol_update() {
	## update the nonvolitile files ## 
	if [ "$host" -ne 0 ] 
	then 
		echo "$host" >> $tabledir/$table
		/sbin/pfctl -f /etc/pf.conf
	else
		echo "No host specified"
		exit 1
	fi
}

live_update() {
	## update tables stored solely within RAM ## 
	if [ "$host" -ne 0 ]
	then
		/sbin/pfctl -t ${table} -T add ${host}
	else
		echo "No host specified"
		exit 1
	fi
}

while getopts ":het:a:" opt
do
	case $opt in
		h)
			run_help
		;;
		t)
			table="$OPTARG"
		;;
		e)
			direct_edit=0
		;;
		a)
			host="$OPTARG"
		;;
		*)
			run_help
		;;
	esac
done

verify
