.POSIX:

include ../../../../defaults.mk

SRC = fsup.c
TARGET = fsup

HELP = "-h"
LDFLAGS = 
DBG = gdb
CFLAGS = -std=c99 -Wall -Wextra -pedantic -Weverything -g${DBG} -O0 -fpic -fpie -fPIE -fPIC -march=native -mtune=native -pipe -fstrict-aliasing
